### ISSUE TITLE
Mute is so mute that there is no documentation available.

### ISSUE THREAD

**Issue by CreoOne** [MuteLang/MuteLang#1]
Judging by MuteLang repositories Den is meant to replace Mute but its dead too.

Refs:
http://wiki.xxiivv.com/mute
http://wiki.xxiivv.com/den

**Comment by renaudbedard** [comment]
Potentially out-of-date test data from when I worked on this project : 

https://github.com/renaudbedard/MuteGrammar/blob/master/full_test_suite.mute
https://github.com/renaudbedard/MuteGrammar/blob/master/demo.mute
